name: image_generator
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  lottie: ^2.2.0
  flutter_riverpod: ^2.1.3
  freezed_annotation: ^2.2.0
  riverpod_annotation: ^1.1.1
  flutter_svg: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3
  riverpod_generator: ^1.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/
