name: image_generator
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  lottie: ^2.2.0
  flutter_svg: ^2.0.0

  cached_network_image: ^3.2.3
  http: ^0.13.5
  image_downloader_web: ^2.0.2
  share_plus: ^6.3.1

  flutter_riverpod: ^2.1.3
  freezed_annotation: ^2.2.0
  riverpod_annotation: ^1.1.1
  
  flutter_dotenv: ^5.0.2
  logger: ^1.1.0
  
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_gallery_saver: ^1.7.1
  flutter_native_splash: ^2.2.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  freezed: ^2.3.2
  build_runner: ^2.3.3
  riverpod_generator: ^1.1.1
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/
    - .env
