# This workflow build and deploy Web app on Gihub Pages.
# Build folder will store on the [deploy-web] branch. This branch is created completely automatically.
name: Build and Deploy Web

on:
  push:
    branches: [main]

  workflow_run:
    workflows: [pull_request_validation]
    types:
      - completed

env:
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  build_web:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Flutter environment
        uses: subosito/flutter-action@v2
        with:
          chanel: 'stable'

      - run: echo "This API_KEY $API_KEY is taken from secret repository on github."

      - name: build web and store [deploy-branch] branch
        uses: bluefireteam/flutter-gh-pages@v7
        with:
          webRenderer: html
          targetBranch: deploy-web
          baseHref: /image_generator/
          customArgs: --target lib/main/main_production.dart --dart-define=API_KEY=$API_KEY
