# This workflow builds, analyses and tests every pull request.
name: Pull Request Validation
on: pull_request
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - name: Check out repository
        uses: actions/checkout@v2
      # Install Flutter environment
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
          chanel: 'stable'
      # Installs the dependencies of the app
      - run: flutter pub get
      # Run code-generators
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs
      # Analyze the code and check for mistakes
      - run: flutter analyze
      